# Generated by Django 4.2.3 on 2024-02-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalystapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.IntegerField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('year_founded', models.IntegerField()),
                ('industry', models.CharField(max_length=13)),
                ('size_range', models.IntegerField()),
                ('locality', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('cme', models.IntegerField()),
                ('tme', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
