# Generated by Django 4.2.3 on 2024-02-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalystapp', '0002_employee_delete_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='keyword',
            field=models.IntegerField(),
        ),
    ]
